export const sampleResumeData = {
  personal: {
    fullName: "Aarav Sharma",
    professionalTitle: "Computer Science Student",
    email: "aarav.sharma.dev@gmail.com",
    phone: "+91 98765 43210",
    linkedin: "linkedin.com/in/aarav-sharma-dev",
    github: "github.com/aaravsharma",
    portfolio: "aaravsharma.dev",
    location: "Noida, Uttar Pradesh",
  },
  summary: "Computer Science student with a strong interest in software development, problem solving, and modern web technologies. Experienced in building academic and personal projects using React, JavaScript, and backend development tools. Known for adaptability, teamwork, and a continuous learning mindset. Seeking internship opportunities to apply technical skills, contribute to impactful projects, and gain practical industry experience.",
  experience: [],
  education: [
    {
      institution: "KCC Institute of Technology and Management",
      level: "Undergraduate",
      degree: "B.Tech",
      branch: "Computer Science and Engineering",
      currentYear: "Third Year",
      graduationYear: "2027",
      score: "",
      coursework: "Data Structures, Operating Systems, Database Management Systems",
    },
    {
      institution: "Delhi Public School",
      level: "Class 12",
      degree: "",
      branch: "Science",
      currentYear: "",
      graduationYear: "2023",
      score: "91%",
      coursework: "Physics, Chemistry, Mathematics, Computer Science",
    },
  ],
  projects: [
    { name: "Campus Placement Portal", technologies: "React.js, Node.js, Express.js, MongoDB", description: "Developed a responsive placement management portal that allows students to browse job opportunities, submit applications, and track application status. Implemented role-based workflows and optimized user experience through reusable React components." },
    { name: "Expense Tracker Application", technologies: "JavaScript, HTML5, CSS3", description: "Built a personal finance management application that helps users track daily expenses, categorize spending patterns, and visualize financial data through an intuitive user interface." },
    { name: "Weather Dashboard", technologies: "React.js, REST APIs", description: "Created a weather forecasting dashboard that retrieves real-time weather information using external APIs and presents location-based forecasts through a clean and responsive interface." },
  ],
  skills: ["JavaScript", "React.js", "Node.js", "Express.js", "MongoDB", "HTML5", "CSS3", "Git", "REST APIs", "SQL", "Problem Solving", "Communication Skills", "Teamwork"],
  certifications: [
    { name: "Google Cloud Computing Foundations", organization: "Google", year: "" },
    { name: "Introduction to Web Development", organization: "IBM SkillsBuild", year: "" },
    { name: "JavaScript Essentials", organization: "Cisco Networking Academy", year: "" },
  ],
  achievements: [
    "Solved 250+ coding problems across coding platforms.",
    "Built and deployed multiple full-stack and frontend projects.",
    "Participated in inter-college hackathons and technical events.",
    "Maintained consistent academic performance while actively pursuing practical development skills.",
  ],
};
