export const DEFAULT_TEMPLATE_ID = "launchpad";

const legacyTemplateAliases = {
  ats: "launchpad",
  modern: "horizon",
  minimal: "swift",
  sidebar: "nexus",
  creative: "elevate",
};

export const resumeTemplates = [
  {
    id: "launchpad",
    name: "LaunchPad",
    tag: "Freshers",
    description: "Clean starter layout for internships and fresher roles.",
    previewKind: "classic",
    accent: "#1e5f4b",
    paperClassName: "px-[6.5%] py-[5.8%] text-[#34433e]",
    pdf: {
      layout: "single",
      accent: "#1e5f4b",
      ink: "#173f33",
      muted: "#64736e",
      soft: "#687772",
      rule: "#9eb3ac",
      marginX: 17,
      marginTop: 16,
      marginBottom: 16,
      titleSize: 19,
      bodySize: 8,
    },
  },
  {
    id: "horizon",
    name: "Horizon",
    tag: "Minimal",
    description: "Minimal layout with a polished modern header.",
    previewKind: "modern",
    accent: "#256f8f",
    paperClassName: "px-[6%] py-[5.5%] text-[#39423f]",
    pdf: {
      layout: "single",
      accent: "#256f8f",
      ink: "#1e3e4b",
      muted: "#5b737c",
      soft: "#63747a",
      rule: "#8fb9c8",
      marginX: 16,
      marginTop: 15,
      marginBottom: 15,
      titleSize: 21,
      bodySize: 8.2,
    },
  },
  {
    id: "swift",
    name: "Swift",
    tag: "ATS Friendly",
    description: "Compact ATS-friendly layout for dense student resumes.",
    previewKind: "minimal",
    accent: "#3c4a45",
    paperClassName: "px-[5.8%] py-[4.8%] text-[#303a36]",
    pdf: {
      layout: "single",
      accent: "#333f3b",
      ink: "#202a26",
      muted: "#626d68",
      soft: "#59635f",
      rule: "#c9d2ce",
      marginX: 14,
      marginTop: 13,
      marginBottom: 13,
      titleSize: 17,
      bodySize: 7.5,
    },
  },
  {
    id: "nexus",
    name: "Summit",
    tag: "Professional",
    description: "Professional sidebar layout for balanced profiles.",
    previewKind: "sidebar",
    accent: "#2d5f73",
    paperClassName: "p-0 text-[#34433e]",
    pdf: {
      layout: "sidebar",
      accent: "#2d5f73",
      ink: "#1c3440",
      muted: "#5b6c73",
      soft: "#5e6f76",
      rule: "#91acb7",
      sidebarBg: "#eaf2f4",
      sidebarWidth: 62,
      marginX: 15,
      marginTop: 15,
      marginBottom: 15,
      titleSize: 18,
      bodySize: 7.9,
    },
  },
  {
    id: "elevate",
    name: "Elevate",
    tag: "Modern",
    description: "Expressive modern layout for standout student resumes.",
    previewKind: "creative",
    accent: "#8058a8",
    paperClassName: "px-[6.3%] py-[5.7%] text-[#393744]",
    pdf: {
      layout: "single",
      accent: "#8058a8",
      ink: "#302b45",
      muted: "#686276",
      soft: "#625d6c",
      rule: "#c3b5df",
      marginX: 16,
      marginTop: 15,
      marginBottom: 15,
      titleSize: 20,
      bodySize: 8,
    },
  },
  {
    id: "executive",
    name: "Sterling",
    tag: "Business & Management",
    description: "Corporate layout for business, leadership, and operations.",
    previewKind: "executive",
    accent: "#334155",
    paperClassName: "px-[6.2%] py-[5.6%] text-[#26323f]",
    pdf: {
      layout: "executive",
      accent: "#334155",
      ink: "#182230",
      muted: "#596879",
      soft: "#637083",
      rule: "#a9b4c1",
      marginX: 16,
      marginTop: 15,
      marginBottom: 15,
      titleSize: 20,
      bodySize: 8,
    },
  },
  {
    id: "nova",
    name: "Nova",
    tag: "Software Engineering",
    description: "Modern layout designed for technical resumes.",
    previewKind: "nova",
    accent: "#0f766e",
    paperClassName: "px-[5.8%] py-[5.2%] text-[#243b3a]",
    pdf: {
      layout: "nova",
      accent: "#0f766e",
      ink: "#113534",
      muted: "#526d6a",
      soft: "#60736f",
      rule: "#8fc7bf",
      marginX: 15,
      marginTop: 14,
      marginBottom: 14,
      titleSize: 21,
      bodySize: 7.8,
    },
  },
  {
    id: "atlas",
    name: "Venture",
    tag: "Project Focused",
    description: "Project-led layout for technical student portfolios.",
    previewKind: "atlas",
    accent: "#1d4ed8",
    paperClassName: "p-0 text-[#253247]",
    pdf: {
      layout: "atlas",
      accent: "#1d4ed8",
      ink: "#172554",
      muted: "#536179",
      soft: "#5e6a7d",
      rule: "#9bb7f0",
      sidebarBg: "#eef4ff",
      sidebarWidth: 54,
      marginX: 14,
      marginTop: 14,
      marginBottom: 14,
      titleSize: 18,
      bodySize: 7.8,
    },
  },
  {
    id: "zenith",
    name: "Insight",
    tag: "Data & Analytics",
    description: "Analytics-oriented layout for data projects and tools.",
    previewKind: "zenith",
    accent: "#7c3aed",
    paperClassName: "px-[6%] py-[5.2%] text-[#342f45]",
    pdf: {
      layout: "zenith",
      accent: "#7c3aed",
      ink: "#2f2352",
      muted: "#665d78",
      soft: "#686175",
      rule: "#c4b5fd",
      marginX: 15,
      marginTop: 14,
      marginBottom: 14,
      titleSize: 20,
      bodySize: 7.9,
    },
  },
  {
    id: "prestige",
    name: "Prestige",
    tag: "Most Popular",
    description: "Premium layout preferred for internships and placements.",
    previewKind: "prestige",
    accent: "#8a6f3d",
    paperClassName: "px-[7%] py-[6%] text-[#302d27]",
    pdf: {
      layout: "prestige",
      accent: "#8a6f3d",
      ink: "#28241d",
      muted: "#6b6255",
      soft: "#6f675d",
      rule: "#d5c7a6",
      marginX: 18,
      marginTop: 17,
      marginBottom: 17,
      titleSize: 19,
      bodySize: 7.8,
    },
  },
];

export const templateIds = resumeTemplates.map((template) => template.id);
export const templateById = Object.fromEntries(resumeTemplates.map((template) => [template.id, template]));

export function normalizeTemplateId(templateId) {
  return legacyTemplateAliases[templateId] || templateId;
}

export function isValidTemplateId(templateId) {
  return templateIds.includes(normalizeTemplateId(templateId));
}

export function getTemplate(templateId) {
  return templateById[normalizeTemplateId(templateId)] || templateById[DEFAULT_TEMPLATE_ID];
}
